export enum UserRole {
  ADMINISTRATOR = "ADMINISTRATOR",
  USER = "USER",
  FARMER = "FARMER",
  TRANSPORTER = "TRANSPORTER",
  RETAILER = "RETAILER",
  QUALITY_INSPECTOR = "QUALITY_INSPECTOR",
  WAREHOUSE_OPERATOR = "WAREHOUSE_OPERATOR",
}

export enum ProductType {
  AGRICULTURE = "AGRICULTURE",
  PHARMACEUTICAL = "PHARMACEUTICAL",
  CREATIVE = "CREATIVE",
  MANUFACTURING = "MANUFACTURING",
}
